#!/usr/bin/env bash
set -ef -o pipefail

AWS_REGION="${AWS_REGION:-eu-west-2}"

function print_help_and_exit() {
  echo "Creates an S3 bucket to store .tfstate files"
  echo ""
  echo "$0 -t <team name> -e <environment> -p <aws profile>"
  echo ""
  echo "<team name>        = team name"
  echo "<environment>      = prod, staging, test, etc"
  echo "<aws profile>      = aws profile name from ~/.aws/credentials"
  exit 1
}

function check_arguments () {
  [ "${TEAMNAME}" ] || print_help_and_exit
  [ "${ENVIRONMENT}" ] || print_help_and_exit
  [ "${AWS_PROFILE}" ] || print_help_and_exit
}

while getopts "t:e:p:" arg; do
  case $arg in
    t)
      TEAMNAME="${OPTARG}"
      ;;
    e)
      ENVIRONMENT="${OPTARG}"
      ;;
    p)
      AWS_PROFILE="${OPTARG}"
      ;;
  esac
done

check_arguments
echo "Creating terraform state bucket tfstate-${TEAMNAME}-${ENVIRONMENT} in ${AWS_REGION}"
aws s3api create-bucket --bucket "tfstate-${TEAMNAME}-${ENVIRONMENT}" --region "${AWS_REGION}" --create-bucket-configuration LocationConstraint="${AWS_REGION}" --profile "${AWS_PROFILE}"
echo "Enabling bucket versioning on tfstate-${TEAMNAME}-${ENVIRONMENT} in ${AWS_REGION}"
aws s3api put-bucket-versioning --bucket "tfstate-${TEAMNAME}-${ENVIRONMENT}" --region "${AWS_REGION}" --versioning-configuration Status=Enabled --profile "${AWS_PROFILE}"
