#!/usr/bin/env bash
#set -x

if [ -z "$JENKINS_HOST" ] || [ -z "$CREDS" ]; then
  echo "** ERROR **: Please run this command again using either of the below commands:"
  echo ""
  echo "Generate list of plugins with specified version:"
  echo " JENKINS_HOST=localhost:8080 CREDS=username:jenkins-api-token ./generate-plugin-list"
  echo ""
  echo "Generate list of plugins and use latest version available:"
  echo " JENKINS_HOST=localhost:8080 CREDS=username:jenkins-api-token ./generate-plugin-list latest"
  echo ""
  echo ""
  echo "jenkins-api-token can be found under a users configuration within jenkins."
  exit 1
fi

if [ "$1" = "latest" ]; then
  echo "** Generating plugins list with latest versions"
  curl --user $CREDS -sSL "http://$JENKINS_HOST/pluginManager/api/xml?depth=1&xpath=/*/*/shortName|/*/*/version&wrapper=plugins" | perl -pe 's/.*?<shortName>([\w-]+).*?<version>([^<]+)()(<\/\w+>)+/\1 \2\n/g'|sed 's/ /:/' | awk -F ":" '{ print $1 ":latest" }' >> ./plugins.txt
else
  echo "** Generating plugins list with current (pinned) versions"
  curl --user $CREDS -sSL "http://$JENKINS_HOST/pluginManager/api/xml?depth=1&xpath=/*/*/shortName|/*/*/version&wrapper=plugins" | perl -pe 's/.*?<shortName>([\w-]+).*?<version>([^<]+)()(<\/\w+>)+/\1 \2\n/g'|sed 's/ /:/' >> ./plugins.txt
fi
